/**
 * G2/G3 audit (runs against saved data; no network).
 * Outputs:
 *  - evidence/audit/rnvda-episodes.json and docs/audit/RNVDA_EPISODES.md (episode-level table)
 *  - evidence/audit/turnover-coverage.json (weekend sessions around 2026-07-09)
 *  - evidence/audit/sensitivity.json (added-assumption sensitivity, separate from canonical results)
 */
import { join } from "node:path";
import { mkdirSync, writeFileSync } from "node:fs";
import { canonicalElapsed, observe } from "../src/domain/episodes";
import { sessionHourlyTurnover, TURNOVER_VALID_FROM_MS, MIN_COMPLETE_HOURS } from "../src/domain/turnover";
import { AGREEMENT_MIN, MIN_ELIGIBLE_EPISODES } from "../src/domain/signal";
import { INTENTS, type ConfirmedIntention, type Intent } from "../src/domain/intent";
import type { Card } from "../src/domain/decision";
import { causesOf } from "../src/domain/causes";
import { BAR_MS, fmtEt, HOUR } from "../src/domain/time";
import { loadDataset, episodesFor } from "../src/server/dataset";
import { allSessionsFor, replayCard } from "../src/server/research";
import { ROOT, log, writeJsonAtomic } from "./lib/fsx";

const SYMBOL = "RNVDAUSDT";
const REF: Record<Intent, { holdingUsdt: number | null; tradeUsdt: number | null }> = {
  HOLD: { holdingUsdt: 2000, tradeUsdt: null },
  BUY_DIP: { holdingUsdt: null, tradeUsdt: 500 },
  SELL_POP: { holdingUsdt: 2000, tradeUsdt: 500 },
};

/** Classify every reason a card stood down (shared classifier in src/domain/causes.ts). */
export function causes(card: Card): string[] {
  return causesOf(card.standDownReasons);
}

function intention(intent: Intent, decisionPrice: number | null): ConfirmedIntention {
  return { symbol: SYMBOL, intent, ...REF[intent], limitPrice: intent === "HOLD" ? null : decisionPrice };
}

function main() {
  const ds = loadDataset();
  const inst = ds.supported.find((i) => i.symbol === SYMBOL)!;
  const idx = ds.bars[SYMBOL];
  const sessions = allSessionsFor(ds, inst, idx.last!);
  const eps = episodesFor(ds, inst, sessions).filter((e) => e.completedAtMs <= idx.last! + BAR_MS);

  // 1. Episode table (canonical methodology)
  const rows = eps.map((e) => {
    const ob = observe(e, idx, canonicalElapsed(e));
    const t = sessionHourlyTurnover(e.session, idx);
    const cards = Object.fromEntries(INTENTS.map((i) => [i, replayCard(ds, intention(i, ob.decisionPrice), e.key).card])) as Record<Intent, Card>;
    const c = cards.HOLD;
    const priceComplete = e.fridayRef !== null && ob.decisionPrice !== null && e.reopenPrice !== null && e.endpointPrice !== null;
    return {
      weekend: e.key,
      lastTradingDay: e.session.lastTradingDay,
      fridayRefTs: fmtEt(e.session.startMs),
      fridayRef: e.fridayRef,
      decisionTs: fmtEt(e.session.canonicalDecisionMs),
      decisionPrice: ob.decisionPrice,
      transitionTs: fmtEt(e.session.transitionMs),
      reopenTs: fmtEt(e.session.reopenMs),
      reopenPrice: e.reopenPrice,
      endpointTs: fmtEt(e.session.endpointMs),
      endpointPrice: e.endpointPrice,
      w: ob.w,
      r: ob.r,
      turnoverCompleteHours: t.completeHours,
      turnoverTotalHours: t.totalHours,
      turnoverEligible: t.eligible,
      turnoverReason: t.reason,
      standard: e.session.standard,
      calendarStatus: e.session.calendarStatus,
      priceComplete,
      cohortEligible: e.baseExclusions.length === 0 && ob.decisionPrice !== null,
      exclusions: [...e.baseExclusions, ...ob.exclusions],
      priorEligibleBeforeDecision: c.signal.eligibleCount,
      evaluated: priceComplete && e.baseExclusions.length === 0 && c.signal.eligibleCount >= MIN_ELIGIBLE_EPISODES,
      threshold: c.signal.threshold,
      matchedExtreme: c.signal.matchedCount,
      signal: c.signal.signal,
      ht: c.ht.value,
      actions: Object.fromEntries(INTENTS.map((i) => [i, cards[i].action])),
      standDownReasons: Object.fromEntries(INTENTS.map((i) => [i, cards[i].standDownReasons])),
      causes: Object.fromEntries(INTENTS.map((i) => [i, causes(cards[i])])),
    };
  });
  mkdirSync(join(ROOT, "evidence", "audit"), { recursive: true });
  writeJsonAtomic(join(ROOT, "evidence", "audit", "rnvda-episodes.json"), { generatedAt: new Date().toISOString(), referenceInputs: REF, rows });

  const n = (v: number | null | undefined, d = 2) => (v === null || v === undefined ? "n/a" : v.toFixed(d));
  const pct = (v: number | null | undefined) => (v === null || v === undefined ? "n/a" : `${(v * 100).toFixed(2)}%`);
  const md: string[] = [
    "# rNVDA episode-level audit table",
    "",
    `Generated by \`npx tsx scripts/audit-g2-g3.ts\` from saved data (snapshot ${String(ds.ingest.finishedAt)}). Canonical methodology; reference inputs as in \`docs/VALIDATION.md\`. Prices are rNVDA token prices in USDT. Times are New York time.`,
    "",
    "| Weekend (Sat) | Friday ref (bar end) | Decision (Sun 20:00 bar end) | Observed transition | Reopen (09:30 bar open) | Endpoint (10:30 bar end) | w | r | Own-session turnover hours complete / total (feeds later H_t only) | Price-complete | Cohort-eligible | Prior eligible at decision | Matched extreme | Evaluated | Actions HOLD / BUY_DIP / SELL_POP | Stand-down causes (HOLD) |",
    "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |",
    ...rows.map(
      (r) =>
        `| ${r.weekend} | ${r.fridayRefTs}: ${n(r.fridayRef, 3)} | ${r.decisionTs}: ${n(r.decisionPrice, 3)} | ${r.transitionTs} | ${r.reopenTs}: ${n(r.reopenPrice, 3)} | ${r.endpointTs}: ${n(r.endpointPrice, 4)} | ${pct(r.w)} | ${pct(r.r)} | ${r.turnoverCompleteHours} / ${r.turnoverTotalHours}${r.turnoverEligible ? "" : " (ineligible)"} | ${r.priceComplete ? "yes" : "no"} | ${r.cohortEligible ? "yes" : "no"} | ${r.priorEligibleBeforeDecision} | ${r.matchedExtreme} | ${r.evaluated ? "yes" : "no"} | ${r.actions.HOLD} / ${r.actions.BUY_DIP} / ${r.actions.SELL_POP} | ${r.causes.HOLD.join(", ")} |`,
    ),
    "",
    "## Exclusion and stand-down reasons by weekend",
    "",
    ...rows.flatMap((r) => [
      `### ${r.weekend}`,
      "",
      `- Exclusions from the cohort: ${r.exclusions.length ? r.exclusions.join("; ") : "none"}`,
      `- Turnover: ${r.turnoverReason ?? "eligible"}`,
      ...INTENTS.map((i) => `- ${i} stand-down reasons: ${r.standDownReasons[i].length ? r.standDownReasons[i].join("; ") : "none (action taken)"}`),
      "",
    ]),
  ];
  mkdirSync(join(ROOT, "docs", "audit"), { recursive: true });
  writeFileSync(join(ROOT, "docs", "audit", "RNVDA_EPISODES.md"), md.join("\n") + "\n", "utf8");

  // 2. Turnover coverage around 2026-07-09
  const coverage = sessions
    .filter((s) => s.startMs >= Date.UTC(2026, 5, 15) && s.startMs <= Date.UTC(2026, 7, 5))
    .map((s) => {
      const bars = idx.range(s.startMs, s.transitionMs);
      const intervals = (s.transitionMs - s.startMs) / BAR_MS;
      let rawCompleteHours = 0;
      for (let h = s.startMs; h + HOUR <= s.transitionMs; h += HOUR) {
        if ([0, 1, 2, 3].every((k) => idx.starting(h + k * BAR_MS)?.quoteTurnover != null)) rawCompleteHours++;
      }
      const tv = bars.map((b) => b.quoteTurnover ?? 0);
      return {
        weekend: s.key,
        start: fmtEt(s.startMs),
        beforeValidityDate: s.startMs < TURNOVER_VALID_FROM_MS,
        weekendIntervals: intervals,
        barsPresent: bars.length,
        barsWithTurnoverValue: bars.filter((b) => b.quoteTurnover !== null).length,
        barsWithZeroTurnover: bars.filter((b) => b.quoteTurnover === 0).length,
        medianBarTurnoverUsdt: tv.length ? [...tv].sort((a, b) => a - b)[Math.floor(tv.length / 2)] : null,
        completeHoursIgnoringDateRule: rawCompleteHours,
        completeHoursCanonical: sessionHourlyTurnover(s, idx).completeHours,
        eligibleCanonical: sessionHourlyTurnover(s, idx).eligible,
        reason: sessionHourlyTurnover(s, idx).reason,
      };
    });
  writeJsonAtomic(join(ROOT, "evidence", "audit", "turnover-coverage.json"), { generatedAt: new Date().toISOString(), turnoverValidFrom: new Date(TURNOVER_VALID_FROM_MS).toISOString(), sessions: coverage });

  // 3. Sensitivity of the two added assumptions (separate from canonical)
  const grid: { minCompleteHours: number; agreementMin: number }[] = [];
  for (const h of [1, 3, 6, 12, 24]) for (const a of [AGREEMENT_MIN, 0]) grid.push({ minCompleteHours: h, agreementMin: a });
  const sens = grid.map((opt) => {
    const perIntent = Object.fromEntries(
      INTENTS.map((intent) => {
        const evaluated = eps
          .map((e) => {
            const ob = observe(e, idx, canonicalElapsed(e));
            const { card } = replayCard(ds, intention(intent, ob.decisionPrice), e.key, opt);
            return { e, card };
          })
          .filter(({ e, card }) => e.baseExclusions.length === 0 && card.observation.decisionPrice !== null && card.signal.eligibleCount >= MIN_ELIGIBLE_EPISODES);
        const causeCount: Record<string, number> = {};
        for (const { card } of evaluated) for (const c of causes(card)) causeCount[c] = (causeCount[c] ?? 0) + 1;
        return [
          intent,
          {
            evaluated: evaluated.length,
            withHt: evaluated.filter(({ card }) => card.ht.value !== null).length,
            actions: evaluated.filter(({ card }) => card.action !== "STAND_DOWN").map(({ e, card }) => `${e.key}:${card.action}`),
            signals: evaluated.map(({ e, card }) => `${e.key}:${card.signal.signal}`),
            causeCount,
          },
        ];
      }),
    );
    return { ...opt, canonical: opt.minCompleteHours === MIN_COMPLETE_HOURS && opt.agreementMin === AGREEMENT_MIN, perIntent };
  });
  writeJsonAtomic(join(ROOT, "evidence", "audit", "sensitivity.json"), { generatedAt: new Date().toISOString(), note: "Sensitivity runs only; canonical results are unchanged.", grid: sens });
  log(`Audit written: ${rows.length} episodes, ${coverage.length} coverage sessions, ${sens.length} sensitivity cases`);
}

main();
